import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Serve static files from the 'dist' directory (generated by npm run build)
// Browsers cannot execute .tsx files directly, so we must serve the built artifacts.
app.use(express.static(path.join(__dirname, 'dist')));

// Handle client-side routing by serving index.html for all non-file requests
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
  console.log('Ensure you have run "npm run build" before starting this server.');
});